### ISSUE TITLE
ModuleNotFoundError: No module named 'moses.utils'

### ISSUE THREAD

**Issue by mapengsen** [mathcom/BPTok#1]
ModuleNotFoundError: No module named 'moses.utils'

**Comment by mathcom** [comment]
Thanks for your interests.
Regretfully, this BPTok repo is incomplete and unavailable yet.

If you seek the source codes of MolGPT, please refer to the original git repository, https://github.com/devalab/molgpt.

**Comment by mapengsen** [comment]
thank you very much!
